3rd party login - fix
uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_007 pull request #93
Opened 2024-11-28 16:47 UTC by Wans-G

Solved several issues causing "login with google" button not to function properly:
1. Indentation Fix in the Session View:
- Corrected an indentation issue in the session view, the button can go to the correct URL.
2. Changed the redirect string format to correctly embed the url
- Make sure you have the .env file like below: (or you use other method to load the var)

```
GOOGLE_CLIENT_ID=917751851506-n3.......
GOOGLE_CLIENT_SECRET=GOCSPX-K-vfD8u_-P7D......
HOST_URL=localhost:3000
```

3.  Added CSRF protection
- new gem in the gem file, it will prevent the CSRF problem
- make sure you bundle install that
4. I loosen the name in registeration to include space between words - since the name retrieved from email is full name
5. TODO: I will add the tests in future updates

The feature should work now, let me know if you get any questions!

2024-11-28 20:22 UTC, bjohnson66 commented on app/models/user.rb
> +  VALID_NAME_REGEX = /\A[^\s]+(\s[^\s]+)*\z/
Does this allow spaces in the names? Is that ok @zhasa18 I think you took that out to use names as usernames? Maybe its ok

2024-11-28 20:26 UTC, bjohnson66 commented on app/views/sessions/new.html.haml
> +    %p.google-login{ style: "margin-top: 10px;" }
No changes?

2024-11-28 20:28 UTC, bjohnson66 commented on config/initializers/omniauth.rb
> +    redirect_uri: "http://#{ENV['HOST_URL']}/auth/google_oauth2/callback"
Whoa whoa... dont we specifically need it to be HTTPS? or it doesn't work? I thought we had issues with that last sprint

2024-11-28 20:30 UTC, bjohnson66 commented on node_modules/.package-lock.json
I think we need to gitignore all the node modules (We shouldn't need this in the repo as it is all code autogenerated by npm run build)

2024-11-28 20:30 UTC, bjohnson66 requested changes
I left comments, I don't think it is ready to merge yet (There are some issues)

2024-11-28 20:47 UTC, zhasa18 commented on app/models/user.rb
> +  VALID_NAME_REGEX = /\A[^\s]+(\s[^\s]+)*\z/
Yea I removed the use of spaces because name is going to become username in the future. I am going to change that in the table. Also, if you make this change, it will cause existing rspecs to fail so you should always run the existing tests to see that your code doesn't conflict with it.

2024-11-28 20:48 UTC, zhasa18 commented on config/initializers/omniauth.rb
> +    redirect_uri: "http://#{ENV['HOST_URL']}/auth/google_oauth2/callback"
Will this not cause issues with the heroku deployment? Or is this just a local fix?

2024-11-28 20:51 UTC, Wans-G commented on config/initializers/omniauth.rb
> +    redirect_uri: "http://#{ENV['HOST_URL']}/auth/google_oauth2/callback"
Hmm I know it should be https, but the google side don't allow me to change it to https. But for the deployment website, it allows https

2024-11-28 20:51 UTC, Wans-G commented on app/views/sessions/new.html.haml
> +    %p.google-login{ style: "margin-top: 10px;" }
what do you expect

2024-11-28 20:57 UTC, Wans-G commented on app/models/user.rb
> +  VALID_NAME_REGEX = /\A[^\s]+(\s[^\s]+)*\z/
I think the user name is not a primay key? Are we going to use email or user name as a identifier?
If there is a confilct, I can replace space with "_"
My test doesn't show any conflict:
bundle exec rspec
....................................................................................................................................

Finished in 3.28 seconds (files took 1.98 seconds to load)
132 examples, 0 failures

2024-11-28 20:59 UTC, Wans-G commented on node_modules/.package-lock.json
You are right, I accidently added those

2024-11-28 21:05 UTC, zhasa18 commented on node_modules/.package-lock.json
Yea we don't need to npm install since we are using the importmap.rb in the config directory. 

When you want to make an import for example importing "@hotwired/turbo-rails"

You would put this command in the terminal:

```./bin/importmap pin @hotwired/turbo-rails```

This way the javascript is saved in a file in the vendor directory, which is much smaller than the node modules directory. 

We should use import map for imports from now on so that we don't add roughly 600 files when node_modules is added.

2024-11-28 21:14 UTC, zhasa18 commented on app/models/user.rb
> +  VALID_NAME_REGEX = /\A[^\s]+(\s[^\s]+)*\z/
Yea you are right. They still seem to pass. But we are still going to use it as a username. I am sorry if I didn't make an announcement about it, just keep it the way it is for now.

2024-11-28 21:15 UTC, Wans-G commented on node_modules/.package-lock.json
Thank you. I have removed the folder

2024-11-28 21:16 UTC, zhasa18 reviewed
Can you please fix the issues I commented on and commit again so I can review it again and approve the merge. Commit and push on the same branch of course!

2024-11-28 21:22 UTC, zhasa18 commented on node_modules/.package-lock.json
Also I forgot to tell you. Include this tag 

```    = javascript_importmap_tags
```

In place of the ```= javascript_include_tag 'application'``` tag on line 7 of the application.html.haml to allow the importmap to work.

2024-11-28 21:26 UTC, Wans-G commented on node_modules/.package-lock.json
okay, will replace that

2024-11-28 21:40 UTC, Wans-G commented on app/models/user.rb
> +  VALID_NAME_REGEX = /\A[^\s]+(\s[^\s]+)*\z/
So do you want me to set the defalut username to like first_mid_last when using the google login?

2024-11-28 21:52 UTC, zhasa18 commented on app/models/user.rb
> +  VALID_NAME_REGEX = /\A[^\s]+(\s[^\s]+)*\z/
Do you need it to be first name and last name for google to work?

2024-11-28 21:56 UTC, Wans-G commented on app/models/user.rb
> +  VALID_NAME_REGEX = /\A[^\s]+(\s[^\s]+)*\z/
can we have a quick call?

2024-11-28 21:58 UTC, zhasa18 commented on app/models/user.rb
> +  VALID_NAME_REGEX = /\A[^\s]+(\s[^\s]+)*\z/
sure

2024-11-28 22:25 UTC, bjohnson66 commented on app/views/sessions/new.html.haml
> +    %p.google-login{ style: "margin-top: 10px;" }
Oh I was just saying when I compare them it looks like there are no actual changes.. just kind of weird. i think its fine as long as it all still works

2024-11-28 22:26 UTC, bjohnson66 commented on config/initializers/omniauth.rb
> +    redirect_uri: "http://#{ENV['HOST_URL']}/auth/google_oauth2/callback"
Ok, so for the things we merge to devel, we should make it be like what goes to heroku (becuase it is going to heroku) can you make sure its https in the pull request?

2024-11-28 22:36 UTC, Wans-G commented on app/views/sessions/new.html.haml
> +    %p.google-login{ style: "margin-top: 10px;" }
Yeah there is no character changes expect spaces, the spaces changed the button behavior. I guess there should be a better way to change it, but ... it works

2024-11-28 22:47 UTC, Wans-G commented
Hi Ziad, @zhasa18  I added 6 unique charaters to the new user name, so all users registered with goolge account should be unique now.(the chance of duplicated user name is 1 in 300 million). They are encouraged to change user name later.

You can check if the branch meets all your requirements

2024-11-28 22:53 UTC, zhasa18 commented
> Hi Ziad, @zhasa18 I added 6 unique charaters to the new user name, so all users registered with goolge account should be unique now, and with no space or numbers in it.(the chance of duplicated user name is 1 in 300 million). They are encouraged to change user name later.
> 
> You can check if the branch meets all your requirements

All right, I will test the branch in like an hourish since I am away from my computer.

2024-11-28 22:57 UTC, Wans-G commented
no problem! thanks

2024-11-29 02:13 UTC, bjohnson66 commented on config/initializers/omniauth.rb
> +    redirect_uri: "#{ENV['HOST_URL']}/auth/google_oauth2/callback"
So right now it is set to:

    redirect_uri: "https://#ENV['HOST_URL']/auth/google_oauth2/callback"


where #ENV['HOST_URL'] evaluates to 'shards-of-the-grid-i2dev-615e05ea270d.herokuapp.com'

so if you don't put https:// it wont be there.... will it work without https: and just


shards-of-the-grid-i2dev-615e05ea270d.herokuapp.com/auth/google_oauth2/callback

2024-11-29 03:32 UTC, bjohnson66 commented on config/initializers/omniauth.rb
> +    redirect_uri: "#{ENV['HOST_URL']}/auth/google_oauth2/callback"
If you use this line it should handle both cases cleanly

redirect_uri: "#{Rails.env.production? ? 'https' : 'http'}://#{ENV['HOST_URL']}/auth/google_oauth2/callback"

2024-11-29 03:42 UTC, Wans-G commented on config/initializers/omniauth.rb
> +    redirect_uri: "#{ENV['HOST_URL']}/auth/google_oauth2/callback"
My thought is put https in the HOST_URL, so we can make it be http when using localhost, and be https in heroku

2024-11-29 03:43 UTC, Wans-G commented on config/initializers/omniauth.rb
> +    redirect_uri: "#{ENV['HOST_URL']}/auth/google_oauth2/callback"
okay I will change that!

2024-11-29 06:48 UTC, bjohnson66 approved these changes
Tests pass, 
still doesnt work on my machine but ive seen it run on yousrs (in practice)

willing to push it to get it to work on heroku

2024-11-29 07:36 UTC, zhasa18 approved these changes
Nice!

2024-11-29 09:03 UTC, merged